server:
  port: 85

eureka:
  instance:
    hostname: rabbitApp
    ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eurekaHost}

spring:
  application:
    name: boot-queue
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #通过实现 ConfirmCallback 接口，消息发送到 Broker 后触发回调，确认消息是否到达 Broker 服务器，也就是只确认是否正确到达 Exchange 中
    publisher-confirms: true
    #启动消息失败返回，比如路由不到队列时触发回调
    publisher-returns: true

  kafka:
    bootstrap-servers: 192.168.1.80:9092


