spring:
  application:
    name: boot-queue
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

server:
  port: 85


eureka:
  instance:
    hostname: rabbitApp
    ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${eurekaHost}



